<?php
 return [
                'sms_user_pay' => '0',
                'sms_user_send' => '0',
                'sms_user_refund' => '0',
                'sms_user_pay_id' => '',
                'sms_user_send_id' => '',
                'sms_user_refund_id' => '',
                'sms_store_pay' => '0',
                'sms_store_refund' => '0',
                'sms_store_pay_id' => '',
                'sms_store_refund_id' => '',
                'gzh_user_pay' => '0',
                'gzh_user_send' => '0',
                'gzh_user_refund' => '0',
                'gzh_user_pay_id' => '',
                'gzh_user_send_id' => '',
                'gzh_user_refund_id' => '',
                'gzh_store_pay' => '0',
                'gzh_store_refund' => '0',
                'gzh_store_pay_id' => '',
                'gzh_store_refund_id' => '',
                'miniapp_user_pay' => '0',
                'miniapp_user_send' => '0',
                'miniapp_user_refund' => '0',
                'miniapp_user_pay_id' => '',
                'miniapp_user_send_id' => '',
                'miniapp_user_refund_id' => ''
            ];