<?php
 return [
                'url' => 'http://192.168.0.100',
                'title' => 'IdeaCMS商城系统(B2C)',
                'logo' => 'cat/cat1.jpg',
                'name' => '老范',
                'phone' => '0832-3971200',
                'tel' => '15680208018',
                'qq' => '289039121',
                'openid' => '',
                'template' => 'skin001',
                'keywords' => 'IdeaCMS商城系统',
                'description' => 'IdeaCMS商城，一款小而美的商城系统！',
                'company' => '隆昌三皮网络科技有限公司',
                'record' => '蜀ICP备10202395号',
                'copyright' => 'Powered by IdeaCMS商城',
                'hot_key' => 'iphone15|小米14|加绒大衣|户外围炉|男运动鞋',
                'open_pc' => '0',
                'app_id' => 'www.myhaopu.shop',
                'api_key' => 'a557f1ce605e50b6',
                'token_ttl' => '10',
                'refresh_token_ttl' => '20',
                'user_reserved_word' => 'admin,manager',
                'user_recharge' => '0',
                'user_recharge_gift' => '0',
                'code_login' => '1',
                'other_login' => '0',
                'log_days' => '30',
                'map_key' => ''
            ];